--region Drop Existing Procedures

IF OBJECT_ID(N'[dbo].[spInsertCliente]') IS NOT NULL
	DROP PROCEDURE [dbo].[spInsertCliente]

--endregion

GO

--region [dbo].[spInsertCliente]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   kerberos using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[spInsertCliente]
-- Date Generated: lunes, 28 de julio de 2014
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[spInsertCliente]
	@Id numeric(5, 0) output,
	@Nombre varchar(100),
	@Apellido varchar(100),
	@TipoIdentificacion varchar(20),
	@NumeroIdentificacion varchar(20),
	@Ecorreo varchar(50),
	@FechaNacimiento datetime,
	@Estado numeric(5, 0),
	@FechaCreacion datetime,
	@FechaEdicion datetime,
	@UsuarioCreacion varchar(25),
	@UsuarioEdicion varchar(25)
AS

SET NOCOUNT ON

INSERT INTO [dbo].[Cliente] (
	[Nombre],
	[Apellido],
	[TipoIdentificacion],
	[NumeroIdentificacion],
	[Ecorreo],
	[FechaNacimiento],
	[Estado],
	[FechaCreacion],
	[FechaEdicion],
	[UsuarioCreacion],
	[UsuarioEdicion]
) VALUES (
	@Nombre,
	@Apellido,
	@TipoIdentificacion,
	@NumeroIdentificacion,
	@Ecorreo,
	@FechaNacimiento,
	@Estado,
	@FechaCreacion,
	@FechaEdicion,
	@UsuarioCreacion,
	@UsuarioEdicion
)
set @Id = @@identity
--endregion

GO

