use PanLucho
go
--region Drop Existing Procedures

IF OBJECT_ID(N'[dbo].[spClienteInsertar]') IS NOT NULL
	DROP PROCEDURE [dbo].[spClienteInsertar]

--endregion

GO

--region [dbo].[spInsertCliente]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   kerberos using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[spInsertCliente]
-- Date Generated: lunes, 28 de julio de 2014
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[spClienteInsertar]
	@Id numeric(5, 0) output,
	@Nombre varchar(100),
	@Apellido varchar(100),
	@TipoIdentificacion varchar(20),
	@NumeroIdentificacion varchar(20),
	@Ecorreo varchar(50),
	@FechaNacimiento datetime,
	@Estado numeric(5, 0),
	@FechaCreacion datetime,
	@FechaEdicion datetime,
	@UsuarioCreacion varchar(25),
	@UsuarioEdicion varchar(25)
AS

SET NOCOUNT ON

INSERT INTO [dbo].[Cliente] (
	[Nombre],
	[Apellido],
	[TipoIdentificacion],
	[NumeroIdentificacion],
	[Ecorreo],
	[FechaNacimiento],
	[Estado],
	[FechaCreacion],
	[FechaEdicion],
	[UsuarioCreacion],
	[UsuarioEdicion]
) VALUES (
	@Nombre,
	@Apellido,
	@TipoIdentificacion,
	@NumeroIdentificacion,
	@Ecorreo,
	@FechaNacimiento,
	@Estado,
	@FechaCreacion,
	@FechaEdicion,
	@UsuarioCreacion,
	@UsuarioEdicion
)
set @Id = @@identity
--endregion

GO

/*
        Autor       :   Usuario
        Notas       :   Derechos de Autor 2013 ESPOL Todos los derechos reservados
        Historia    :   
                        29/07/2014
*/
CREATE PROCEDURE [dbo].spClienteEliminar
@Id numeric(5, 0)
AS

DELETE FROM
[dbo].[Cliente]
WHERE
[Id] = @Id
GO

/*
        Autor       :   Usuario
        Notas       :   Derechos de Autor 2013 ESPOL Todos los derechos reservados
        Historia    :   
                        29/07/2014
*/
CREATE PROCEDURE [dbo].spClienteObtener
@Id numeric(5, 0)
AS

SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
[Id],
[Nombre],
[Apellido],
[TipoIdentificacion],
[NumeroIdentificacion],
[Ecorreo],
[FechaNacimiento],
[Estado],
[FechaCreacion],
[FechaEdicion],
[UsuarioCreacion],
[UsuarioEdicion]
FROM
[dbo].[Cliente]
WHERE
[Id] = @Id

GO

/*
        Autor       :   Usuario
        Notas       :   Derechos de Autor 2013 ESPOL Todos los derechos reservados
        Historia    :   
                        29/07/2014
*/

CREATE PROCEDURE [dbo].spClienteObtenerLista
AS

SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
[Id],
[Nombre],
[Apellido],
[TipoIdentificacion],
[NumeroIdentificacion],
[Ecorreo],
[FechaNacimiento],
[Estado],
[FechaCreacion],
[FechaEdicion],
[UsuarioCreacion],
[UsuarioEdicion]
FROM
[dbo].[Cliente]

GO




/*
        Autor       :   Usuario
        Notas       :   Derechos de Autor 2013 ESPOL Todos los derechos reservados
        Historia    :   
                        29/07/2014
*/

CREATE PROCEDURE [dbo].spClienteActualizar
@Id numeric(5, 0), 
@Nombre varchar(100), 
@Apellido varchar(100), 
@TipoIdentificacion varchar(20), 
@NumeroIdentificacion varchar(20), 
@Ecorreo varchar(50), 
@FechaNacimiento datetime, 
@Estado numeric(5, 0), 
@FechaCreacion datetime, 
@FechaEdicion datetime, 
@UsuarioCreacion varchar(25), 
@UsuarioEdicion varchar(25) 
AS

UPDATE [dbo].[Cliente] SET
[Nombre] = @Nombre,
[Apellido] = @Apellido,
[TipoIdentificacion] = @TipoIdentificacion,
[NumeroIdentificacion] = @NumeroIdentificacion,
[Ecorreo] = @Ecorreo,
[FechaNacimiento] = @FechaNacimiento,
[Estado] = @Estado,
[FechaCreacion] = @FechaCreacion,
[FechaEdicion] = @FechaEdicion,
[UsuarioCreacion] = @UsuarioCreacion,
[UsuarioEdicion] = @UsuarioEdicion
WHERE
[Id] = @Id

GO


------------------------------------------------------------------------------------------------------------------------
/*
        Autor       :   Usuario
        Notas       :   Derechos de Autor 2013 ESPOL Todos los derechos reservados
        Historia    :   
                        30/07/2014
*/
CREATE PROCEDURE [dbo].spUsuarioEliminar
@Id numeric(5, 0)
AS

DELETE FROM
[dbo].[Usuario]
WHERE
[Id] = @Id
GO

/*
        Autor       :   Usuario
        Notas       :   Derechos de Autor 2013 ESPOL Todos los derechos reservados
        Historia    :   
                        30/07/2014
*/
CREATE PROCEDURE [dbo].spUsuarioObtener
@Id numeric(5, 0)
AS

SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
[Id],
[IdRol],
[Nombre],
[Apellido],
[Ecorreo],
[Identificacion],
[Contrasena],
[FechaCreacion],
[FechaEdicion],
[IdEstado]
FROM
[dbo].[Usuario]
WHERE
[Id] = @Id

GO



/*
        Autor       :   Usuario
        Notas       :   Derechos de Autor 2014 ESPOL Todos los derechos reservados
        Historia    :   
                        30/07/2014
*/

CREATE PROCEDURE [dbo].spUsuarioObtenerLista
AS

SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
[Id],
[IdRol],
[Nombre],
[Apellido],
[Ecorreo],
[Identificacion],
[Contrasena],
[FechaCreacion],
[FechaEdicion],
[IdEstado]
FROM
[dbo].[Usuario]

GO


/*
        Autor       :   Usuario
        Notas       :   Derechos de Autor 2013 ESPOL Todos los derechos reservados
        Historia    :   
                        30/07/2014
*/

CREATE PROCEDURE [dbo].spUsuarioInsertar
@Id numeric(5, 0) output,
@IdRol numeric(5, 0),
@Nombre varchar(100),
@Apellido varchar(100),
@Ecorreo varchar(50),
@Identificacion varchar(13),
@Contrasena varchar(50),
@FechaCreacion datetime,
@FechaEdicion datetime,
@IdEstado numeric(5, 0)
AS

INSERT INTO [dbo].[Usuario] (
[IdRol],
[Nombre],
[Apellido],
[Ecorreo],
[Identificacion],
[Contrasena],
[FechaCreacion],
[FechaEdicion],
[IdEstado]
) VALUES (
@IdRol,
@Nombre,
@Apellido,
@Ecorreo,
@Identificacion,
@Contrasena,
@FechaCreacion,
@FechaEdicion,
@IdEstado
)
set @Id = @@identity
GO

/*
        Autor       :   Usuario
        Notas       :   Derechos de Autor 2013 ESPOL Todos los derechos reservados
        Historia    :   
                        30/07/2014
*/

CREATE PROCEDURE [dbo].spUsuarioActualizar
@Id numeric(5, 0), 
@IdRol numeric(5, 0), 
@Nombre varchar(100), 
@Apellido varchar(100), 
@Ecorreo nchar(10), 
@Identificacion varchar(25), 
@Contrasena varchar(50), 
@FechaCreacion datetime, 
@FechaEdicion datetime, 
@IdEstado numeric(5, 0) 
AS

UPDATE [dbo].[Usuario] SET
[IdRol] = @IdRol,
[Nombre] = @Nombre,
[Apellido] = @Apellido,
[Ecorreo] = @Ecorreo,
[Identificacion] = @Identificacion,
[Contrasena] = @Contrasena,
[FechaCreacion] = @FechaCreacion,
[FechaEdicion] = @FechaEdicion,
[IdEstado] = @IdEstado
WHERE
[Id] = @Id

GO

CREATE PROCEDURE [dbo].[spProductoObtenerParaFactura]
	@Id numeric(5, 0)
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
	[Descripcion],
	[DescripcionDetallada],
	[UnidadMedida],
	[Existencias],
	[Precio]
FROM
	[dbo].[Producto]
WHERE
	[Id] = @Id

--endregion

GO

CREATE PROCEDURE [dbo].[spProductoObtener]
	@Id numeric(5, 0)
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
	[Descripcion],
	[DescripcionDetallada],
	[ClaseProducto],
	[UnidadMedida],
	[Existencias],
	[Precio],
	[IdEstado],
	[EsGrabado],
	[FechaCreacion],
	[FechaEdicion],
	[UsuarioCreacion],
	[UsuarioEdicion]
FROM
	[dbo].[Producto]
WHERE
	[Id] = @Id

--endregion
GO

/****** Objecto:  StoredProcedure [dbo].[spProductosOtenerParaVenta]  ******/
------------------------------------------------------------------------------------------------------------------------
/*
        Autor       :   Usuario
        Notas       :   Derechos de Autor 2014 ESPOL Todos los derechos reservados
        Historia    :   
                        17/08/2014
		exec spProductosObtenerParaVenta @Filtro=MOL,@Estado=1,@EsCodigo=0
		exec spProductosObtenerParaVenta @Filtro=1	,@Estado=1,@EsCodigo=1
*/
CREATE PROCEDURE [dbo].[spProductosObtenerParaVenta]
	@Filtro				varchar(15),
	@Estado				numeric(5,0),
	@EsCodigo			bit
AS
	select		Id						=	prd.Id,
				Descripcion				=	prd.Descripcion,
				DescripcionDetallada	=	prd.DescripcionDetallada,
				ClaseProducto			=	prd.ClaseProducto,
				UnidadMedida			=	prd.UnidadMedida,
				Existencias				=	prd.Existencias,
				Precio					=	prd.Precio,
				IdEstado				=	prd.IdEstado,
				EsGrabado				=	prd.EsGrabado,
				FechaCreacion			=	prd.FechaCreacion,
				FechaEdicion			=	prd.FechaEdicion,
				UsuarioCreacion			=	prd.UsuarioCreacion,
				UsuarioEdicion			=	prd.UsuarioEdicion				
	from		dbo.Producto		prd		with(nolock)				
	where		prd.Id					=	(
												case	@EsCodigo
												when	1		then	@Filtro	
												else					prd.Id
												end
											)
				and 
				DescripcionDetallada	like(
												case	@EsCodigo
												when	0		then '%' + @Filtro + '%'
												else					   prd.DescripcionDetallada
												end
											)	
				and 
				IdEstado = @Estado
GO


/*
        Autor       :   Usuario
        Notas       :   Derechos de Autor 2014 ESPOL Todos los derechos reservados
        Historia    :   
                        19/08/2014
*/
CREATE PROCEDURE [dbo].spModuloObtener
@Id numeric(5, 0)
AS

SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
[Id],
[IdModuloCategoria],
[Nombre],
[Descripcion],
[Assembler],
[LibreriaClase],
[NombreFormulario],
[Imagen],
[FechaCreacion],
[FechaEdicion],
[IdEstado],
[UsuarioEdicion]
FROM
[dbo].[Modulo]
WHERE
[Id] = @Id

GO

/*
        Autor       :   Usuario
        Notas       :   Derechos de Autor 2014 ESPOL Todos los derechos reservados
        Historia    :   
                        19/08/2014
*/

CREATE PROCEDURE [dbo].spModuloObtenerLista
AS

SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
[Id],
[IdModuloCategoria],
[Nombre],
[Descripcion],
[Assembler],
[LibreriaClase],
[NombreFormulario],
[Imagen],
[FechaCreacion],
[FechaEdicion],
[IdEstado],
[UsuarioEdicion]
FROM
[dbo].[Modulo]

GO


/*
        Autor       :   Usuario
        Notas       :   Derechos de Autor 2013 ESPOL Todos los derechos reservados
        Historia    :   
                        19/08/2014
*/
CREATE PROCEDURE [dbo].spModuloCategoriaObtener
@Id numeric(5, 0)
AS

SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
[Id],
[Nombre],
[Descripcion],
[FechaCreacion],
[FechaEdicion],
[IdEstado],
[UsuarioEdicion]
FROM
[dbo].[ModuloCategoria]
WHERE
[Id] = @Id

GO

/*
        Autor       :   Usuario
        Notas       :   Derechos de Autor 2013 ESPOL Todos los derechos reservados
        Historia    :   
                        19/08/2014
*/

CREATE PROCEDURE [dbo].spModuloCategoriaObtenerLista
AS

SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
[Id],
[Nombre],
[Descripcion],
[FechaCreacion],
[FechaEdicion],
[IdEstado],
[UsuarioEdicion]
FROM
[dbo].[ModuloCategoria]

GO



/*
        Autor       :   Usuario
        Notas       :   Derechos de Autor 2013 ESPOL Todos los derechos reservados
        Historia    :   
                        19/08/2014
*/
CREATE PROCEDURE [dbo].spRolEliminar
@Id numeric(5, 0)
AS

DELETE FROM
[dbo].[Rol]
WHERE
[Id] = @Id
GO

/*
        Autor       :   Usuario
        Notas       :   Derechos de Autor 2013 ESPOL Todos los derechos reservados
        Historia    :   
                        19/08/2014
*/
CREATE PROCEDURE [dbo].spRolObtener
@Id numeric(5, 0)
AS

SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
[Id],
[Nombre],
[Descripcion],
[IdEstado]
FROM
[dbo].[Rol]
WHERE
[Id] = @Id

GO

/*
        Autor       :   Usuario
        Notas       :   Derechos de Autor 2013 ESPOL Todos los derechos reservados
        Historia    :   
                        19/08/2014
*/

CREATE PROCEDURE [dbo].spRolObtenerLista
AS

SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
[Id],
[Nombre],
[Descripcion],
[IdEstado]
FROM
[dbo].[Rol]

GO


/*
        Autor       :   Usuario
        Notas       :   Derechos de Autor 2013 ESPOL Todos los derechos reservados
        Historia    :   
                        19/08/2014
*/

CREATE PROCEDURE [dbo].spRolInsertar
@Id numeric(5, 0) output,
@Nombre varchar(20),
@Descripcion varchar(20),
@IdEstado numeric(5, 0)
AS

-- THIS STORED PROCEDURE NEEDS TO BE MANUALLY COMPLETED
-- MULITPLE PRIMARY KEY MEMBERS OR NON-GUID/INT PRIMARY KEY

INSERT INTO [dbo].[Rol] (
[Nombre],
[Descripcion],
[IdEstado]
) VALUES (
@Nombre,
@Descripcion,
@IdEstado
)
set @Id = @@identity

GO

/*
        Autor       :   Usuario
        Notas       :   Derechos de Autor 2013 ESPOL Todos los derechos reservados
        Historia    :   
                        19/08/2014
*/

CREATE PROCEDURE [dbo].spRolActualizar
@Id numeric(5, 0), 
@Nombre varchar(20), 
@Descripcion varchar(20), 
@IdEstado numeric(5, 0) 
AS

UPDATE [dbo].[Rol] SET
[Nombre] = @Nombre,
[Descripcion] = @Descripcion,
[IdEstado] = @IdEstado
WHERE
[Id] = @Id

GO



/*
        Autor       :   Usuario
        Notas       :   Derechos de Autor 2014 ESPOL Todos los derechos reservados
        Historia    :   
                        19/08/2014
*/

CREATE PROCEDURE [dbo].spModulosXRolInsertar
@Id numeric(5, 0) output,
@IdRol numeric(5, 0),
@IdModulo numeric(5, 0),
@Parametros nvarchar(10)
AS

-- THIS STORED PROCEDURE NEEDS TO BE MANUALLY COMPLETED
-- MULITPLE PRIMARY KEY MEMBERS OR NON-GUID/INT PRIMARY KEY

INSERT INTO [dbo].[ModulosXRol] (
[IdRol],
[IdModulo],
[Parametros]
) VALUES (
@IdRol,
@IdModulo,
@Parametros
)
set @Id = @@identity
GO



/*
        Autor       :   Usuario
        Notas       :   Derechos de Autor 2014 ESPOL Todos los derechos reservados
        Historia    :   
                        24/08/2014
*/
CREATE PROCEDURE [dbo].spModulosXRolEliminar
@IdRol numeric(5, 0)
AS

DELETE FROM
[dbo].[ModulosXRol]
WHERE
[IdRol] = @IdRol
GO



/*
        Autor       :   Usuario
        Notas       :   Derechos de Autor 2014 ESPOL Todos los derechos reservados
        Historia    :   
                        24/08/2014
*/
CREATE PROCEDURE [dbo].spEventoObtenerLista
AS

SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
[Id],
[Descripcion],
[IdEstado]
FROM
[dbo].[Evento]
GO

--region [dbo].[spInsertFacturaCab]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   kerberos using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[spInsertFacturaCab]
-- Date Generated: domingo, 24 de agosto de 2014
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[spFacturaCabInsert]
	@Id numeric(5, 0) output,
	@IdCliente numeric(5, 0),
	@FechaFacturacion datetime,
	@FacturaSRI varchar(max),
	@SubTotal money,
	@IVA money,
	@Descuento money,
	@TotalPagar money,
	@FechaCreacion datetime,
	@UserCreador varchar(25),
	@Procesado bit,
	@EsCancelado bit,
	@IdSucursal numeric(5, 0)
AS

SET NOCOUNT ON

INSERT INTO [dbo].[FacturaCab] (
	
	[IdCliente],
	[FechaFacturacion],
	[FacturaSRI],
	[SubTotal],
	[IVA],
	[Descuento],
	[TotalPagar],
	[FechaCreacion],
	[UserCreador],
	[Procesado],
	[EsCancelado],
	[IdSucursal]
) VALUES (
	
	@IdCliente,
	@FechaFacturacion,
	@FacturaSRI,
	@SubTotal,
	@IVA,
	@Descuento,
	@TotalPagar,
	@FechaCreacion,
	@UserCreador,
	@Procesado,
	@EsCancelado,
	@IdSucursal
)
set @Id = @@identity
--endregion
GO

--region [dbo].[spInsertFacturaDetalle]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   kerberos using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[spInsertFacturaDetalle]
-- Date Generated: domingo, 24 de agosto de 2014
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[spFacturaDetalleInsert]
	@IdFacturaCab numeric(5, 0),
	@linea numeric(5, 0),
	@IdProducto numeric(5, 0),
	@Cantidad numeric(9, 0),
	@TotalLinea smallmoney,
	@Iva numeric(4, 2),
	@DescuentoPorcentaje numeric(4, 2),
	@DescuentoValor numeric(4, 2)
AS

SET NOCOUNT ON

INSERT INTO [dbo].[FacturaDetalle] (
	[IdFacturaCab],
	[linea],
	[IdProducto],
	[Cantidad],
	[TotalLinea],
	[Iva],
	[DescuentoPorcentaje],
	[DescuentoValor]
) VALUES (
	@IdFacturaCab,
	@linea,
	@IdProducto,
	@Cantidad,
	@TotalLinea,
	@Iva,
	@DescuentoPorcentaje,
	@DescuentoValor
)
--endregion

GO


/*
        Autor       :   Usuario
        Notas       :   Derechos de Autor 2014 ESPOL Todos los derechos reservados
        Historia    :   
                        26/08/2014
*/

CREATE PROCEDURE [dbo].spOrdenEspecialCabInsertar
@Id numeric(5, 0) output,
@IdCliente numeric(5, 0),
@SubTotal money,
@IVA money,
@Abono money,
@FechaEntrega date,
@FechaCreacion datetime,
@UserCreador varchar(25),
@IdEstado numeric(5, 0)
AS

-- THIS STORED PROCEDURE NEEDS TO BE MANUALLY COMPLETED
-- MULITPLE PRIMARY KEY MEMBERS OR NON-GUID/INT PRIMARY KEY

INSERT INTO [dbo].[OrdenEspecialCab] (
[IdCliente],
[SubTotal],
[IVA],
[Abono],
[FechaEntrega],
[FechaCreacion],
[UserCreador],
[IdEstado]
) VALUES (
@IdCliente,
@SubTotal,
@IVA,
@Abono,
@FechaEntrega,
@FechaCreacion,
@UserCreador,
@IdEstado
)
set @Id = @@identity
GO



/*
        Autor       :   Usuario
        Notas       :   Derechos de Autor 2014 ESPOL Todos los derechos reservados
        Historia    :   
                        26/08/2014
*/

CREATE PROCEDURE [dbo].spOrdenEspecialDetalleInsertar
@IdOrdenEspecialCab numeric(5, 0),
@Linea numeric(5, 0),
@IdProducto numeric(5, 0),
@Cantidad numeric(9, 0),
@IdEvento numeric(5, 0),
@Color nvarchar(10),
@Leyenda nvarchar(30),
@Imagen varbinary(max),
@Observaciones nvarchar(70)
AS

-- THIS STORED PROCEDURE NEEDS TO BE MANUALLY COMPLETED
-- MULITPLE PRIMARY KEY MEMBERS OR NON-GUID/INT PRIMARY KEY

INSERT INTO [dbo].[OrdenEspecialDetalle] (
[IdOrdenEspecialCab],
[Linea],
[IdProducto],
[Cantidad],
[IdEvento],
[Color],
[Leyenda],
[Imagen],
[Observaciones]
) VALUES (
@IdOrdenEspecialCab,
@Linea,
@IdProducto,
@Cantidad,
@IdEvento,
@Color,
@Leyenda,
@Imagen,
@Observaciones
)
GO